apiVersion: v1
kind: Service
metadata:
  name: sylvia-iot-core
spec:
  selector:
    app: sylvia-iot-core
  ports:
    - name: http
      port: 1080
      targetPort: 1080
    - name: https
      port: 1443
      targetPort: 1443
