apiVersion: apps/v1
kind: Deployment
metadata:
  name: sylvia-iot-data
spec:
  selector:
    matchLabels:
      app: sylvia-iot-data
  template:
    metadata:
      labels:
        app: sylvia-iot-data
    spec:
      containers:
        - name: sylvia-iot-data
          envFrom:
            - configMapRef:
                name: sylvia-iot-data-configmap
          image: sylvia-iot-data
          ports:
            - containerPort: 1080
            - containerPort: 1443
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
            requests:
              cpu: "100m"
              memory: "64Mi"
          volumeMounts:
            - name: certificates
              mountPath: /conf/certs
      volumes:
        - name: certificates
          configMap:
            name: certificates
