apiVersion: v1
kind: Service
metadata:
  name: emqx
spec:
  selector:
    app: emqx
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: mqtts
      port: 8883
      targetPort: 8883
    - name: management
      port: 18083
      targetPort: 18083
