apiVersion: v1
kind: PersistentVolume
metadata:
  name: emqx
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /db/emqx
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  #storageClassName: manual
