apiVersion: v1
kind: Service
metadata:
  name: sylvia-iot-simple-ui
spec:
  selector:
    app: sylvia-iot-simple-ui
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
